#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
REVIEW_DIR=${REVIEW_DIR:-runtime/translation}
EVIDENCE_DIR=${EVIDENCE_DIR:-runtime/handover}
OUTPUT_PATH=${OUTPUT_PATH:-}
EXPORT_PATH=${EXPORT_PATH:-}
DRY_RUN_REPORT_PATH=${DRY_RUN_REPORT_PATH:-}
IMPORT_REPORT_PATH=${IMPORT_REPORT_PATH:-}
AUDIT_REPORT_PATH=${AUDIT_REPORT_PATH:-}
REVIEWER=${REVIEWER:-}
REVIEW_SIGNOFF=${REVIEW_SIGNOFF:-PENDING}
IMAGE_TEXT_SIGNOFF=${IMAGE_TEXT_SIGNOFF:-PENDING}
REMAINING_RISK_REFERENCE=${REMAINING_RISK_REFERENCE:-}
FAIL_ON_PENDING=${FAIL_ON_PENDING:-0}

cd "$ROOT"

resolve_path() {
  case "$1" in
    /*|[A-Za-z]:*) printf '%s\n' "$1" ;;
    *) printf '%s\n' "$ROOT/$1" ;;
  esac
}

latest_file() {
  dir=$(resolve_path "$1")
  pattern=$2
  [ -d "$dir" ] || return 0
  find "$dir" -maxdepth 1 -type f -name "$pattern" 2>/dev/null | sort | tail -n 1
}

normalize_status() {
  value=$(printf '%s' "$1" | tr '[:lower:]' '[:upper:]')
  case "$value" in
    PASS|WARN|FAIL|PENDING|BLOCKED) printf '%s\n' "$value" ;;
    "") printf '%s\n' PENDING ;;
    *) printf '%s\n' WARN ;;
  esac
}

read_result() {
  path=$1
  if [ "$path" = "" ] || [ ! -f "$path" ]; then
    printf '%s\n' PENDING
    return
  fi
  result=$(sed -n -E 's/^- (Result|Status): (PASS|WARN|FAIL)[[:space:]]*$/\2/p' "$path" | head -n 1)
  [ "$result" != "" ] && printf '%s\n' "$result" || printf '%s\n' PASS
}

file_status() {
  path=$1
  [ "$path" != "" ] && [ -f "$path" ] && printf '%s\n' PASS || printf '%s\n' PENDING
}

add_row() {
  area=$1
  status=$2
  evidence=$3
  reference=$4
  notes=$5
  printf '| %s | %s | %s | %s | %s |\n' "$area" "$status" "$evidence" "$reference" "$notes" >> "$ROWS"
  case "$status" in
    FAIL|UNKNOWN) FAILURES=$((FAILURES + 1)) ;;
    WARN|BLOCKED) WARNINGS=$((WARNINGS + 1)) ;;
    PENDING) PENDING=$((PENDING + 1)) ;;
  esac
}

csv_stats() {
  path=$1
  if [ "$path" = "" ] || [ ! -f "$path" ]; then
    printf '%s\n' "0 0 0 0 0"
    return
  fi
  awk -F, '
    NR == 1 {
      for (i = 1; i <= NF; i++) {
        gsub(/^\xef\xbb\xbf/, "", $i)
        h[$i] = i
      }
      next
    }
    NF > 0 {
      rows++
      if (h["needs_review"] && toupper($h["needs_review"]) == "YES") needs++
      if (h["review_translation"] && $h["review_translation"] != "") filled++
      if (h["review_status"] && tolower($h["review_status"]) == "approved") approved++
      if (h["review_status"] && tolower($h["review_status"]) == "image-text") image++
    }
    END { printf "%d %d %d %d %d\n", rows + 0, needs + 0, filled + 0, approved + 0, image + 0 }
  ' "$path"
}

if [ "$OUTPUT_PATH" = "" ]; then
  OUTPUT_PATH="runtime/handover/mongoyia-mongolian-review-evidence-$(date +%Y%m%d-%H%M%S).md"
fi
OUT=$(resolve_path "$OUTPUT_PATH")
mkdir -p "$(dirname "$OUT")"
ROWS="$OUT.rows.tmp"
: > "$ROWS"

FAILURES=0
WARNINGS=0
PENDING=0

[ "$EXPORT_PATH" = "" ] && EXPORT_PATH=$(latest_file "$REVIEW_DIR" 'mn-review*.csv' || true) || EXPORT_PATH=$(resolve_path "$EXPORT_PATH")
[ "$DRY_RUN_REPORT_PATH" = "" ] && DRY_RUN_REPORT_PATH=$(latest_file "$REVIEW_DIR" 'mn-review-*dry*.csv' || true) || DRY_RUN_REPORT_PATH=$(resolve_path "$DRY_RUN_REPORT_PATH")
[ "$IMPORT_REPORT_PATH" = "" ] && IMPORT_REPORT_PATH=$(latest_file "$REVIEW_DIR" 'mn-review-import-*.csv' || true) || IMPORT_REPORT_PATH=$(resolve_path "$IMPORT_REPORT_PATH")
if [ "$AUDIT_REPORT_PATH" = "" ]; then
  AUDIT_REPORT_PATH=$(latest_file runtime/acceptance 'mongoyia-translation-audit-*.md' || true)
  [ "$AUDIT_REPORT_PATH" = "" ] && AUDIT_REPORT_PATH=$(latest_file "$EVIDENCE_DIR" 'mongoyia-translation-audit-*.md' || true)
else
  AUDIT_REPORT_PATH=$(resolve_path "$AUDIT_REPORT_PATH")
fi

set -- $(csv_stats "$EXPORT_PATH")
EXPORTED_ROWS=$1
NEEDS_REVIEW=$2
FILLED_REVIEW=$3
APPROVED_ROWS=$4
IMAGE_TEXT_ROWS=$5

add_row "Review CSV export" "$(file_status "$EXPORT_PATH")" "Latest Mongolian product/category review export" "$EXPORT_PATH" "Generated by mongoyia-translation-review/run."
add_row "Review dry-run report" "$(file_status "$DRY_RUN_REPORT_PATH")" "Review CSV check or dry-run import report" "$DRY_RUN_REPORT_PATH" "Generated before any database apply."
add_row "Review apply/import report" "$(file_status "$IMPORT_REPORT_PATH")" "Reviewed translation import report" "$IMPORT_REPORT_PATH" "Required before production if human corrections are applied."
add_row "Translation audit" "$(read_result "$AUDIT_REPORT_PATH")" "Latest translation audit report" "$AUDIT_REPORT_PATH" "Run after review/import to confirm remaining language risks."
add_row "Native/business signoff" "$(normalize_status "$REVIEW_SIGNOFF")" "Human Mongolian content review signoff" "$REVIEWER" "Set PASS only after reviewer approval."
add_row "Image text review" "$(normalize_status "$IMAGE_TEXT_SIGNOFF")" "Embedded Chinese text in product/category images reviewed" "$REMAINING_RISK_REFERENCE" "Record ticket/sheet reference only."

if [ "$FAILURES" -gt 0 ]; then RESULT=FAIL
elif [ "$PENDING" -gt 0 ] && [ "$FAIL_ON_PENDING" = "1" ]; then RESULT=FAIL
elif [ "$WARNINGS" -gt 0 ] || [ "$PENDING" -gt 0 ]; then RESULT=WARN
else RESULT=PASS
fi

{
  echo "# Mongoyia Mongolian Review Evidence"
  echo
  echo "- Result: $RESULT"
  echo "- Failures: $FAILURES"
  echo "- Warnings: $WARNINGS"
  echo "- Pending: $PENDING"
  echo "- Generated at: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "- Reviewer: $REVIEWER"
  echo "- Review dir: $(resolve_path "$REVIEW_DIR")"
  echo "- Evidence dir: $(resolve_path "$EVIDENCE_DIR")"
  echo
  echo "This report is read-only. It does not translate text, import CSV rows, restore databases, or modify content."
  echo
  echo "| Area | Status | Evidence | Reference | Notes |"
  echo "|---|---:|---|---|---|"
  cat "$ROWS"
  echo
  echo "## Review CSV Stats"
  echo
  echo "| Metric | Count |"
  echo "|---|---:|"
  echo "| Exported rows | $EXPORTED_ROWS |"
  echo "| Rows flagged needs_review | $NEEDS_REVIEW |"
  echo "| Rows with review_translation | $FILLED_REVIEW |"
  echo "| Rows marked approved | $APPROVED_ROWS |"
  echo "| Rows marked image-text | $IMAGE_TEXT_ROWS |"
  echo
  echo "## Required Review Loop"
  echo
  echo '```bash'
  echo 'php yii mongoyia-translation-review/run --output=@runtime/translation/mn-review.csv --interactive=0'
  echo 'php yii mongoyia-translation-review/check --input=@runtime/translation/mn-review.csv --report=@runtime/translation/mn-review-check.csv --interactive=0'
  echo 'php yii mongoyia-translation-review/import --dryRun=1 --input=@runtime/translation/mn-review.csv --report=@runtime/translation/mn-review-import-dry-run.csv --interactive=0'
  echo 'php yii mongoyia-translation-review/import --dryRun=0 --input=@runtime/translation/mn-review.csv --report=@runtime/translation/mn-review-import-apply.csv --interactive=0'
  echo 'php yii mongoyia-translation-audit/run --interactive=0'
  echo '```'
  echo
  echo 'For final production signoff, rerun this script with `FAIL_ON_PENDING=1`, `REVIEW_SIGNOFF=PASS`, and `IMAGE_TEXT_SIGNOFF=PASS` after native/business review and embedded-image text review are complete.'
} > "$OUT"
rm -f "$ROWS"

echo "Mongoyia Mongolian review evidence: $RESULT"
echo "Report: $OUT"
[ "$FAILURES" -eq 0 ] && { [ "$FAIL_ON_PENDING" != "1" ] || [ "$PENDING" -eq 0 ]; }
